# Generated by Django 2.2.4 on 2021-11-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_auto_20211029_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platillos', models.TextField(verbose_name='Platillos')),
                ('prioridad', models.CharField(max_length=255, verbose_name='Prioridad')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantApp.Mesa')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
