# Generated by Django 2.2.7 on 2021-11-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_savedcarts_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
